### ISSUE TITLE
Governance system

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-system-contracts#41]
As a blockchain user, I would like a governance system that allows stake holders to allow for the promotion of contracts to system contracts and system call overrides.

---

**Governance database record structure**
`| Proposal ID | Vote start block | Vote tally | Shall authorize`
**Note:** Proposal ID is simply the transaction ID of the proposal submitted

**Governance thresholds**
System call override/system contract promotion: 60%
Governance upgrade: 75%

**Proposal notes**
The payer should be set to the governance contract ID and the payee should be set to the account where the nonce will be incremented when the proposal is applied.

---

- [x] koinos/koinos-system-contracts#50
- [x] koinos/koinos-system-contracts#51
- [x] koinos/koinos-system-contracts#52
- [x] koinos/koinos-system-contracts#53
- [x] koinos/koinos-system-contracts#54
- [x] koinos/koinos-system-contracts#56
- [x] koinos/koinos-system-contracts-as#1

---

**Integration test**
- Launch a network using genesis data that gives KOIN to the proposer
- Proposer will create a proposal through governance contract that override a system call returning a value we can verify
- We manually create blocks using `submit_block` RPC directly from code with votes just shy of the threshold of 60% during the vote period
- Verify that no chance to the system call has occurred
- Re-submit the same proposal and call `submit_block` with votes that exceed the 60% threshold
- Check that the system call has been overridden
- Proposer proposes undoing governance
- Create blocks just shy of the 75% threshold
- Verify governance has not changed
- Proposer poses undoing governance
- Verify governance contract is no longer applicable

---

**Review period:** Time in which the proposal has been submitted but voting has not commenced (1 week)
**Vote period:** Time in which block producers may submit votes on the proposal (2 week)
**Application delay:** Time in which the voting period has ended and before the transaction is applied (2 week)
**Minimum proposal denominator:** The denominator used when considering the total supply to provide the minimum proposal burn fee (default 1000000)
**Maximum proposal multiplier:** The multiplier used when considering the RC limit of the proposal transaction for the burn fee (default 10)
